apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: fluentd
  name: fluentd
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fluentd
  template:
    metadata:
      labels:
        app: fluentd
    spec:
      containers:
      - image: fluent/fluentd
        imagePullPolicy: IfNotPresent
        name: fluentd
        ports:
        - containerPort: 8538
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 100m
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
