apiVersion: v1
kind: Service
metadata:
  name: fluentd-svc
  labels:
    app: fluentd-svc
spec:
  ports:
  - name: fluentd-svc-port
    protocol: TCP
    port: 24224
    targetPort: 24224
  selector:
    app: fluentd
